data:
  test_dir: "/data/ahmed.ghorbel/workdir/autod/backup/data/tracks/test_nag4"
  map_dir: "/data/ahmed.ghorbel/workdir/autod/backup/data/maps/filtered/filtered_nag4_46"
  subset_size: 116

sample:
  num_sampling: 50
  num_sampling_steps: 500
  cfg_scale: 4.0
  cuda_device: 0
  seed: 0

model:
  ckpt: "/data/ahmed.ghorbel/workdir/autod/traffic-diffuser/results/001-TrafficDiffuser-S/checkpoints/0148000.pt"
  module: "models.backbones.model_td_gvmp"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-S"
  num_agents: 4
  seq_length: 5
  hist_length: 8
  dim_size: 2
  use_map_embed: True    
