data:
  train_dir: "/data/tii/data/merged/train"
  subset_size: 51_200

train:
  results_dir: "results"
  epochs: 4000
  diffusion_steps: 1000
  learning_rate: 1e-4
  weight_decay: 0        # set to 1e-5 if you need L2 regularization (in case of overfitting)
  global_batch_size: 32
  global_seed: 0
  num_workers: 4
  log_every: 1600
  ckpt_every: 1600_000
  seed: 0

model:
  module: "models.backbones.model_td"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-L"
  max_num_agents: 20
  seq_length: 5
  hist_length: 8
  dim_size: 2
  map_channels: 4
  use_map_embed: False
  use_ckpt_wrapper: True 
