data:
  test_dir: "/data/ahmed.ghorbel/workdir/autod/backup/data/tracks/test_nag4"
  subset_size: 116

sample:
  num_sampling: 50
  num_sampling_steps: 500
  cuda_device: 0
  seed: 0

model:
  ckpt: "/data/ahmed.ghorbel/workdir/autod/traffic-diffuser/results/000-TrafficDiffuser-S/checkpoints/0148000.pt"
  module: "models.backbones.model_td"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-S"
  max_num_agents: 4
  seq_length: 5
  hist_length: 8
  dim_size: 2 
