data:
  train_dir: "/data/ahmed.ghorbel/workdir/autod/backup/data/tracks/train_nag4"  # 450 train and 116 test
  map_dir: "/data/ahmed.ghorbel/workdir/autod/backup/data/maps/filtered/filtered_nag4_46"
  #subset_size: 0
  
train:
  results_dir: "results"
  epochs: 4000
  diffusion_steps: 1000
  learning_rate: 1e-4
  weight_decay: 1e-5  
  global_batch_size: 12
  global_seed: 0
  num_workers: 4
  log_every: 37
  ckpt_every: 37_000
  seed: 0

model:
  module: "models.backbones.model_td_gvmp"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-S"
  num_agents: 4
  seq_length: 5
  hist_length: 8
  dim_size: 2
  use_map_embed: True
  use_ckpt_wrapper: False 
