data:
  test_dir: "/data/tii/data/nuscenes/nuscenes_trainval_clean_test"

sample:
  num_sampling: 100
  num_sampling_steps: 1000
  cuda_device: 0
  seed: 0

model:
  ckpt: "/path/to/checkpoint/0084000.pt"
  model_module: "model_td"
  model: "TrafficDiffuser-S"      # Options: TrafficDiffuser-{S, B, L}
  max_num_agents: 46
  seq_length: 5
  hist_length: 8
  dim_size: 2
  use_map_embed: true    
