data:
  test_dir: "/data/tii/data/autod/test_s100"
  subset_size: 640

sample:
  num_sampling: 100
  num_sampling_steps: 100
  cuda_device: 0
  seed: 0

model:
  ckpt: "results/002-TrafficDiffuser-S/checkpoints/0400000.pt"
  module: "models.backbones.model_td"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-S"
  max_num_agents: 20
  seq_length: 5
  hist_length: 8
  dim_size: 2
  map_channels: 4
  use_map_embed: False    
