data:
  test_dir: "/data/tii/data/merged/test_av2"
  subset_size: 640

sample:
  num_sampling: 100
  num_sampling_steps: 500
  cuda_device: 0
  seed: 0

model:
  ckpt: "/data/ahmed.ghorbel/workdir/autod/traffic-diffuser/results/002-TrafficDiffuser-S/checkpoints/6400000.pt"
  module: "models.backbones.model_td"
  class: "TrafficDiffuser_models"
  name: "TrafficDiffuser-S"
  max_num_agents: 20
  seq_length: 5
  hist_length: 8
  dim_size: 2
  map_channels: 4
  use_map_embed: False    
